server:
  port: ${random.int[10240,65536]}
spring:
  cloud:
    discovery:
      enabled: false
    kubernetes:
      discovery:
        catalog-services-watch:
          enabled: false
ribbon:
  okhttp:
    enabled: false